project_id = "gkayxohjywqyjbisxtit"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.share-meta]
    verify_jwt = false
