// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-coaches.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var search_coaches_default = defineTool({
  name: "search_coaches",
  title: "Search coaches",
  description: "Search Aytopus coaches and service providers by free-text query and/or service category. Returns public profile summaries with rating and review counts.",
  inputSchema: {
    query: z.string().trim().max(120).optional().describe("Free-text search matched against username, display name, and bio."),
    category: z.string().trim().max(60).optional().describe("Service category filter (e.g. 'Coaching', 'Consulting', 'Fitness')."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("profiles").select(
      "username, display_name, bio, service_category, review_count, rating_sum, follower_count, avatar_url"
    ).limit(limit ?? 20);
    if (category) q = q.eq("service_category", category);
    if (query && query.length > 0) {
      const like = `%${query.replace(/[%_]/g, "")}%`;
      q = q.or(`username.ilike.${like},display_name.ilike.${like},bio.ilike.${like}`);
    }
    q = q.order("review_count", { ascending: false });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      username: r.username,
      display_name: r.display_name,
      bio: r.bio,
      service_category: r.service_category,
      review_count: r.review_count,
      average_rating: r.review_count && r.review_count > 0 ? Math.round((r.rating_sum ?? 0) / r.review_count * 10) / 10 : null,
      follower_count: r.follower_count,
      profile_url: `https://aytopus.com/@${r.username}`,
      avatar_url: r.avatar_url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { results: rows }
    };
  }
});

// src/lib/mcp/tools/get-coach-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_coach_profile_default = defineTool2({
  name: "get_coach_profile",
  title: "Get coach profile",
  description: "Fetch the public Aytopus profile of a coach or service provider by their username (without the leading @).",
  inputSchema: {
    username: z2.string().trim().min(1).max(60).describe("Aytopus username, no @ prefix.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ username }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("profiles").select(
      "username, display_name, bio, service_category, review_count, rating_sum, follower_count, avatar_url, website_url, instagram_url, twitter_url, youtube_url, linkedin_url, tiktok_url, created_at"
    ).eq("username", username).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `No profile found for @${username}` }],
        isError: true
      };
    const profile = {
      ...data,
      average_rating: data.review_count && data.review_count > 0 ? Math.round((data.rating_sum ?? 0) / data.review_count * 10) / 10 : null,
      profile_url: `https://aytopus.com/@${data.username}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-coach-reviews.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_coach_reviews_default = defineTool3({
  name: "list_coach_reviews",
  title: "List coach reviews",
  description: "List verified reviews written for an Aytopus coach or service provider, identified by username.",
  inputSchema: {
    username: z3.string().trim().min(1).max(60).describe("Aytopus username, no @ prefix."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max reviews to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ username, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data: prof, error: pErr } = await supabase.from("profiles").select("id, username, display_name").eq("username", username).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!prof)
      return { content: [{ type: "text", text: `No profile found for @${username}` }], isError: true };
    const { data, error } = await supabase.rpc("list_provider_reviews", { p_provider: prof.id });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const reviews = (data ?? []).slice(0, limit ?? 20).map((r) => ({
      id: r.id,
      rating: r.rating,
      body: r.body,
      reviewer_name: r.reviewer_name,
      is_detailed: r.is_detailed,
      completeness_score: r.completeness_score,
      created_at: r.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(reviews, null, 2) }],
      structuredContent: { username: prof.username, reviews }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my Aytopus profile",
  description: "Return the authenticated Aytopus user's own profile (username, display name, category, review counts, socials).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select(
      "username, display_name, bio, service_category, review_count, rating_sum, follower_count, avatar_url, website_url, instagram_url, twitter_url, youtube_url, linkedin_url, tiktok_url, provider_type, role, created_at"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    const profile = {
      ...data,
      average_rating: data.review_count && data.review_count > 0 ? Math.round((data.rating_sum ?? 0) / data.review_count * 10) / 10 : null,
      profile_url: `https://aytopus.com/@${data.username}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gkayxohjywqyjbisxtit";
var mcp_default = defineMcp({
  name: "aytopus-mcp",
  title: "Aytopus",
  version: "0.1.0",
  instructions: "Tools for Aytopus, a review platform for coaches and service providers. Use search_coaches to discover providers by keyword or category, get_coach_profile for a specific @username, list_coach_reviews for verified reviews on a provider, and get_my_profile for the signed-in user's own profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_coaches_default, get_coach_profile_default, list_coach_reviews_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
